peft:
  _target_: megatron.bridge.peft.lora.MemorySparseAttentionLoRA
  dim: 128
  alpha: 256
  dropout: 0.0
  target_modules: ["linear_qkv", "linear_proj", "linear_fc1", "linear_fc2", "router"]
  lora_dtype: bfloat16
  lora_A_init_method: kaiming
  train_memory_proj: true
  train_memory_injector: true

model:
  attention_type: msa # full, swa
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 1
  expert_model_parallel_size: 4
  sequence_parallel: true
  seq_length: 8192
  group_size: 4
  segment_size: 1024
  m2t_mode: block_diag  # "block_diag" or "segment"
  m2m_mode: None      # "causal" or None
  # seg0_lora_bypass: true  # Zero LoRA contribution for first segment_size tokens in MSA layers
  recompute_granularity: "full"
  recompute_method: "uniform"
  recompute_num_layers: 1

ddp:
  overlap_grad_reduce: false

train:
  train_iters: 1 # 3000
  micro_batch_size: 1
  global_batch_size: 32
  distill_alpha: 1.0
  distill_beta: 1.0
  distill_temperature: 1.0
  use_jsd: false
  train_memory_compression_projection: true
  train_memory_qkv_projection: true
  train_common_qkv_projection: false

optimizer:
  lr: 1e-4
  min_lr: 1e-5

scheduler:
  lr_warmup_iters: 500
  lr_decay_style: cosine
  lr_decay_iters: 3000

logger:
  log_interval: 1

validation:
  eval_iters: 2000

checkpoint:
  save: null

dataset:
  dataset_root: "/root/paddlejob/amfp-inference-public/wanghaoshuang/data/megatron_sft_fixed"
  seq_length: 8192
  dataloader_type: "cyclic"
  memmap_workers: 32
  do_validation: false
  do_test: false
  seed: 5678
  dataset_kwargs: {
    "chat": False,
    "use_hf_tokenizer_chat_template": False,
    "add_bos": False,
    "pad_to_max_length": False,
    "answer_only_loss": False,
    "truncation_field": "input"
  }

tokenizer:
  eos_token: "<|im_end|>"
  pad_token_id: 0
